name: Lifailon
description: 📚 Large base of PowerShell notes in Russian language
avatar: https://avatars.githubusercontent.com/u/116945542?s=400&u=a0265b8aff463b2b6814705dffc04894954d0a59&v=4
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Lifailon/PS-Commands
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
disqus:
google_analytics:
url: https://lifailon.github.io
# Если вы размещаете свой сайт в репозитории проекта на страницах GitHub (http://yourusername.github.io/repository-name)
# и НЕ в пользовательском репозитории (http://yourusername.github.io), тогда добавьте сюда baseurl, например: "/repository-name"
baseurl: ""
