title = "PowerShell Commands / RuDocs"
base_url = "https://lifailon.github.io"
description = "Web version for PowerShell notes in Russian language (Сheat Sheet & Documentation) and RuDocs (node.js)"

compile_sass = true
minify_html = true
generate_feeds = true

feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Lifailon"
default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

theme = "duckquill"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

# [languages.ru]
# title = "PowerShell Commands / RuDocs"
# description = "Веб версия заметок PowerShell на русском языке."
# generate_feeds = true
# taxonomies = [{ name = "tags", feed = true }]

[extra]
default_theme = "dark"
accent_color = "#ff7800"
accent_color_dark = "#ffa348"
fix_contrast = true
fix_contrast_dark = true

# emoji_favicon = "🦆"
# favicon = "/docs/Logo/PowerShell-Logo.png"
# logo = "/docs/Logo/PowerShell-Logo.png"

source_url = "https://github.com/Lifailon/PS-Commands"
issues_url = "https://github.com/Lifailon/PS-Commands/issues"

show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true

csp = [
	{ directive = "font-src", domains = ["'self'"] },
	{ directive = "img-src", domains = ["'self'", "https:", "data:"] },
	{ directive = "media-src", domains = ["'self'", "https:"] },
	{ directive = "script-src", domains = ["'self'"] },
	{ directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
	{ directive = "frame-src", domains = ["https://player.vimeo.com", "https://www.youtube-nocookie.com", "https://toot.community"] },
	{ directive = "connect-src", domains = ["https://toot.community"] },
	{ directive = "frame-ancestors", domains = ["'none'"] },
	{ directive = "base-uri", domains = ["'none'"] },
	{ directive = "form-action", domains = ["'none'"] }
]

[extra.nav]
auto_hide = true
show_feed = false
show_theme_switcher = true
show_repo = true

links = [
  { url = "@/PowerShell/index.md", name = "PowerShell" },
  { url = "@/Linux/index.md", name = "Linux" },
  { url = "@/Docker/index.md", name = "Docker" },
  { url = "@/WindowsServer/index.md", name = "Windows Server" },
  { url = "@/Database/index.md", name = "Database" },
  { url = "@/DevOps/index.md", name = "DevOps" },
  { url = "@/Node-js/index.md", name = "Node.js" },
  { url = "@/GoLang/index.md", name = "Go" }
]

[extra.footer]
links = [
  { url = "@/PowerShell/index.md", name = "PowerShell" },
  { url = "@/Linux/index.md", name = "Linux" },
  { url = "@/Docker/index.md", name = "Docker" },
  { url = "@/WindowsServer/index.md", name = "Windows Server" },
  { url = "@/Database/index.md", name = "Database" },
  { url = "@/DevOps/index.md", name = "DevOps" },
  { url = "@/Node-js/index.md", name = "Node.js" },
  { url = "@/GoLang/index.md", name = "Go" }
]

copyright = "© **2023-2024** `Lifailon`"
show_copyright = true
show_source = true
show_powered_by = true
socials = [
	{ url = "https://github.com/lifailon/PS-Commands", name = "GitHub", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EGitHub%3C/title%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E" },
	{ url = "https://www.nuget.org/profiles/Lifailon", name = "NuGet", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ENUGet%3C/title%3E%3Cpath d='M1.57 0A1.57 1.57 0 000 1.57v20.86A1.57 1.57 0 001.57 24h20.86A1.57 1.57 0 0024 22.43V1.57A1.57 1.57 0 0022.43 0zM7.5 1.5A2.5 2.5 0 0110 4a2.5 2.5 0 01-2.5 2.5A2.5 2.5 0 015 4a2.5 2.5 0 012.5-2.5zM12 6h9v12h-1.5a3.76 3.76 0 00-2.81-1.25A3.76 3.76 0 0012.5 20a3.76 3.76 0 002.19 3.25A3.76 3.76 0 0018.5 24H21V6z'/%3E%3C/svg%3E" }
]